In [1]:
import numpy as np
import tensorflow as tf

/usr/local/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


In [2]:
t = np.array(
  [0., 1., 2., 3., 4., 5.,]
)
print(t.ndim)
print(t.shape)
print(t[0])
print(t[2:5])

1
(6,)
0.0
[2. 3. 4.]


In [3]:
t = np.array(
  [[1., 2., 3.], [1., 2., 3.], [1., 2., 3.], [1., 2., 3.]]
)
print(t.ndim)
print(t.shape)

2
(4, 3)


In [4]:
sess = tf.Session()

In [5]:
t = tf.constant([1,2,3,4])
tf.shape(t).eval(session=sess)

array([4], dtype=int32)

In [6]:
t = tf.constant([[1,2],[3,4]])
tf.shape(t).eval(session=sess)

array([2, 2], dtype=int32)

In [7]:
t = tf.constant([[[[1,2,3],[3,4,5]]]])
tf.shape(t).eval(session=sess)

array([1, 1, 2, 3], dtype=int32)

In [8]:
matrix1 = tf.constant([[1., 2.], [3., 4.]])
matrix2 = tf.constant([[1.], [2.]])
print(matrix1.shape)
print(matrix2.shape)
tf.matmul(matrix1, matrix2).eval(session=sess)

(2, 2)
(2, 1)


array([[ 5.],
       [11.]], dtype=float32)

In [9]:
(matrix1 * matrix2).eval(session=sess)

array([[1., 2.],
       [6., 8.]], dtype=float32)

In [10]:
matrix1 = tf.constant([[3., 3.]])
matrix2 = tf.constant([[2., 2.]])
(matrix1 + matrix2).eval(session=sess)

array([[5., 5.]], dtype=float32)

In [11]:
tf.reduce_mean([1, 2], axis=0).eval(session=sess)

1

In [12]:
x = [
    [1., 2.], 
    [3., 4.]
]
tf.reduce_mean(x).eval(session=sess)

2.5

In [13]:
tf.reduce_mean(x, axis=0).eval(session=sess)

array([2., 3.], dtype=float32)

In [14]:
tf.reduce_mean(x, axis=-1).eval(session=sess)

array([1.5, 3.5], dtype=float32)

In [15]:
tf.reduce_sum(x, axis=1).eval(session=sess)

array([3., 7.], dtype=float32)

In [16]:
tf.reduce_sum(x, axis=0).eval(session=sess)

array([4., 6.], dtype=float32)

In [17]:
tf.reduce_mean(tf.reduce_sum(x, axis=0)).eval(session=sess)

5.0

In [18]:
x = [
    [0, 1, 2],
    [2, 1, 0]
]

In [19]:
tf.argmax(x, axis=0).eval(session=sess)

array([1, 0, 0])

In [20]:
tf.argmax(x, axis=1).eval(session=sess)

array([2, 0])

In [21]:
tf.argmax(x, axis=-1).eval(session=sess)

array([2, 0])

In [22]:
t = np.array(
  [[[0, 1, 2], [3,4,5]], [[6, 7,8], [9, 10 ,11]]]
)
t.shape

(2, 2, 3)

In [23]:
tf.reshape(t, shape=[-1, 3]).eval(session=sess)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [24]:
tf.reshape(t, shape=[-1, 4]).eval(session=sess)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [25]:
tf.squeeze([[0], [1], [2]]).eval(session=sess)

array([0, 1, 2], dtype=int32)

In [26]:
tf.expand_dims([[0], [1], [2]], 1).eval(session=sess)

array([[[0]],

       [[1]],

       [[2]]], dtype=int32)

In [27]:
tf.one_hot([[0], [1], [2], [0]], depth=10).eval(session=sess)

array([[[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.]],

       [[0., 1., 0., 0., 0., 0., 0., 0., 0., 0.]],

       [[0., 0., 1., 0., 0., 0., 0., 0., 0., 0.]],

       [[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.]]], dtype=float32)

In [28]:
t = tf.one_hot([[0], [1], [2], [0]], depth=10).eval(session=sess)
tf.reshape(t, shape=[-1, 2]).eval(session=sess)

array([[1., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 1.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [1., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [1., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]], dtype=float32)

In [29]:
tf.cast([True, False], tf.int32).eval(session=sess)

array([1, 0], dtype=int32)

In [30]:
x = y = z = [1 ,4]

In [31]:
tf.stack([x, y, z], axis=1).eval(session=sess)

array([[1, 1, 1],
       [4, 4, 4]], dtype=int32)

In [32]:
x = [[0, 1, 2], [2, 1, 0]]
tf.ones_like(x).eval(session=sess)

array([[1, 1, 1],
       [1, 1, 1]], dtype=int32)

In [33]:
tf.zeros_like(x).eval(session=sess)

array([[0, 0, 0],
       [0, 0, 0]], dtype=int32)

In [34]:
for x, y in zip([1,2,3], [4,5,6]):
  print(x,y)

1 4
2 5
3 6
